### ISSUE TITLE
Test bug in the Aloha exercise

### ISSUE THREAD

**Issue by mikesjewett** [Bloc/workshop-html-css#17]
@getaaron check out this stunning video I made: http://screencast.com/t/nC7tGWRVs

**Comment by getaaron** [comment]
@mikesjewett The issue is the use of a JavaScript-style `/* comment */` which I guess makes the Nokogiri tag parsing ambiguous. If you switch to a valid `<!-- html comment -->` then it works fine.

Do you want me to investigate further? Fixing this would likely involve submitting a patch to Nokogiri

**Comment by mikesjewett** [comment]
Oh, didn't catch that. Yeah I think we can close. Thanks.
